
<div align='center'><img src="dataset-cover.png" alt="Crocos" width="400"><br>
<h1>Crocodile Dataset from Kaggle</h1>
<a href="https://www.kaggle.com/datasets/zadafiyabhrami/global-crocodile-species-dataset">Link to Kaggle</a></div>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
crocodile = pd.read_csv("../data/crocodile_dataset.csv")

In [ ]:
crocodile.shape # row, columns

(1000, 15)

In [ ]:
crocodile.head()

,Observation ID,Common Name,Scientific Name,Family,Genus,Observed Length (m),Observed Weight (kg),Age Class,Sex,Date of Observation,Country/Region,Habitat Type,Conservation Status,Observer Name,Notes
0,1,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,1.90,62.0,Adult,Male,31-03-2018,Belize,Swamps,Least Concern,Allison Hill,Cause bill scientist nation opportunity.
1,2,American Crocodile,Crocodylus acutus,Crocodylidae,Crocodylus,4.09,334.5,Adult,Male,28-01-2015,Venezuela,Mangroves,Vulnerable,Brandon Hall,Ago current practice nation determine operatio...
2,3,Orinoco Crocodile,Crocodylus intermedius,Crocodylidae,Crocodylus,1.08,118.2,Juvenile,Unknown,07-12-2010,Venezuela,Flooded Savannas,Critically Endangered,Melissa Peterson,Democratic shake bill here grow gas enough ana...
3,4,Morelet's Crocodile,Crocodylus moreletii,Crocodylidae,Crocodylus,2.42,90.4,Adult,Male,01-11-2019,Mexico,Rivers,Least Concern,Edward Fuller,Officer relate animal direction eye bag do.
4,5,Mugger Crocodile (Marsh Crocodile),Crocodylus palustris,Crocodylidae,Crocodylus,3.75,269.4,Adult,Unknown,15-07-2019,India,Rivers,Vulnerable,Donald Reid,Class great prove reduce raise author play mov...

In [ ]:
crocodile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Observation ID        1000 non-null   int64
 1   Common Name           1000 non-null   object
 2   Scientific Name       1000 non-null   object
 3   Family                1000 non-null   object
 4   Genus                 1000 non-null   object
 5   Observed Length (m)   1000 non-null   float64
 6   Observed Weight (kg)  1000 non-null   float64
 7   Age Class             1000 non-null   object
 8   Sex                   1000 non-null   object
 9   Date of Observation   1000 non-null   object
 10  Country/Region        1000 non-null   object
 11  Habitat Type          1000 non-null   object
 12  Conservation Status   1000 non-null   object
 13  Observer Name         1000 non-null   object
 14  Notes                 1000 non-null   object
dtypes: float64(2), int64(1), object(12)
memory usage: 117.3+ KB

In [ ]:
crocodile.describe()

       Observation ID  Observed Length (m)  Observed Weight (kg)
count     1000.000000          1000.000000           1000.000000
mean       500.500000             2.415110            155.771900
std        288.819436             1.097542            175.186788
min          1.000000             0.140000              4.400000
25%        250.750000             1.637500             53.225000
50%        500.500000             2.430000            100.600000
75%        750.250000             3.010000            168.875000
max       1000.000000             6.120000           1139.700000

In [ ]:
crocodile.isnull().sum()

Observation ID          0
Common Name             0
Scientific Name         0
Family                  0
Genus                   0
Observed Length (m)     0
Observed Weight (kg)    0
Age Class               0
Sex                     0
Date of Observation     0
Country/Region          0
Habitat Type            0
Conservation Status     0
Observer Name           0
Notes                   0
dtype: int64

In [ ]:
crocodile.duplicated().sum()

np.int64(0)

In [ ]:
crocodile.isnull().any()

Observation ID          False
Common Name             False
Scientific Name         False
Family                  False
Genus                   False
Observed Length (m)     False
Observed Weight (kg)    False
Age Class               False
Sex                     False
Date of Observation     False
Country/Region          False
Habitat Type            False
Conservation Status     False
Observer Name           False
Notes                   False
dtype: bool

In [ ]:
crocodile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Observation ID        1000 non-null   int64
 1   Common Name           1000 non-null   object
 2   Scientific Name       1000 non-null   object
 3   Family                1000 non-null   object
 4   Genus                 1000 non-null   object
 5   Observed Length (m)   1000 non-null   float64
 6   Observed Weight (kg)  1000 non-null   float64
 7   Age Class             1000 non-null   object
 8   Sex                   1000 non-null   object
 9   Date of Observation   1000 non-null   object
 10  Country/Region        1000 non-null   object
 11  Habitat Type          1000 non-null   object
 12  Conservation Status   1000 non-null   object
 13  Observer Name         1000 non-null   object
 14  Notes                 1000 non-null   object
dtypes: float64(2), int64(1), object(12)
memory usage: 117.3+ KB

In [ ]:
print(crocodile.columns)

Index(['Observation ID', 'Common Name', 'Scientific Name', 'Family', 'Genus',
       'Observed Length (m)', 'Observed Weight (kg)', 'Age Class', 'Sex',
       'Date of Observation', 'Country/Region', 'Habitat Type',
       'Conservation Status', 'Observer Name', 'Notes'],
      dtype='object')